---
# Goal:
# - Determine which RPI's are online.
# - Check if they're freshly flashed (new image), if so, convert it into master/worker node
# - Install OLED system on each device
# - Set up k3s on master and workers

- name: Finding hosts
  hosts: localhost
  gather_facts: no
  roles:
    - find_hosts

- name: Set up freshly flashed devices
  hosts: defaultdevices
  ignore_unreachable: yes
  become: yes
  roles:
    - setup-pi
  ignore_errors: true

# - name: Set up OLED display
#   hosts:
#     - master
#     - nodes
#   become: yes
#   roles:
#     - setup-oled

- name: Install k3s on master
  hosts:
    - master
  become: yes
  roles:
    - install-k3s/general
    - install-k3s/master
  vars:
    install_k3s: false

- name: Install k3s on nodes
  hosts:
    - nodes
  become: yes
  roles:
    - install-k3s/general
    - install-k3s/node
  vars:
    install_k3s: true
