---

# Goal:
# - Determine which RPI's are online.
# - Check if they're freshly flashed (new image)
# - If not, check which one is the master
# -         The rest are nodes


- name: Finding hosts
  hosts: localhost
  gather_facts: no
  roles:
    - find_hosts


# Now we have three groups:
#  - defaultdevices
#  - master
#  - nodes 


# Apply roles to the found raspberry pi('s)
- name: Set up freshly flashed devices
  hosts: defaultdevices
  become: yes
  roles: 
    - setup-pi
  ignore_errors: true


- name: Set up OLED display
  hosts: #defaultdevices
    - master
    - nodes
  become: yes
  roles:
    - setup-oled


- name: Install Docker
  hosts: #defaultdevices
    - master
    - nodes
  become: yes
  roles:
    - install-docker


- name: Install k3s on master
  hosts: 
    - master
  become: yes
  roles:
    - install-k3s/general
    - install-k3s/master


- name: Install k3s on nodes
  hosts: 
    - nodes
  become: yes
  roles:
    - install-k3s/general
    - install-k3s/node
  vars:
    install_k3s: true


    
        
    
