---

# Apply roles to the found raspberry pi('s)
- name: Set up freshly flashed devices
  hosts: defaultdevices
  become: yes
  roles: 
    - setup-pi
    - setup-oled
    - check-reboot
    
        
    
