---
- name: Finding hosts
  hosts: localhost
  gather_facts: no
  roles:
    - find_hosts


- name: Install k3s on master
  hosts: 
    - master
  become: yes
  roles:
    - install-k3s/master
  vars:
    install_k3s: false


- name: Install k3s on nodes
  hosts: 
    - nodes
  become: yes
  roles:
    - install-k3s/node
  vars:
    install_k3s: false


    
        
    
