---

# Change pi's password

- name: Change password
  expect:
    command: passwd pi
    responses:
      (?i)password: "{{ node_password }}"

# Deploy ssh key
- name: Deploy SSH key
  authorized_key: user=pi
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                  state=present
                  


