---
# Alle common items hier
- name: Install needed packages
  become: yes
  apt: 
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages: 
    - build-essential
    - python-dev
    - python-pip
    - python-imaging
    - python-smbus
    - git
    
- name: "(pip) Install RPI.GPIO"
  pip:
    name: RPI.GPIO
    
- name: "Install Adafruit's SSD1306 module from git"
  become: yes
  become_user: pi
  git:
    repo: "https://github.com/adafruit/Adafruit_Python_SSD1306.git"
    dest: "~/Adafruit_Python_SSD1306"
    
- name: "Run setup.py"
  command: python /home/pi/Adafruit_Python_SSD1306/setup.py install
  become: yes
  become_method: su
    
- name: "Test run OLED"
  command: python /home/pi/Adafruit_Python_SSD1306/examples/image.py
  become: yes
    
    
 
