---
# First, change the timezone
#  Remove /etc/localtime
#  echo "Europe/Amsterdam" > /etc/timezone
#  run dpkg-reconfigre
- name: Remove old timezone
  file: path='/etc/localtime' state=absent

- name: Set new timezone
  command: "echo 'Europe/Amsterdam' > /etc/timezone"

- name: Run dpkg-reconfigure
  command: "dpkg-reconfigure -f noninteractive tzdata"


# Next, change the locale to en_US
#  Disable GB, enable US,
#  Change and regenerate locales
- name: Remove GB locale
  lineinfile: 
    path: /etc/locale.gen
    regex: 'en_GB.UTF-8 UTF-8'
    line: '#en_GB.UTF-8 UTF-8'

- name: Enable {{ node_locale }}
  lineinfile: 
    path: /etc/locale.gen
    regex: '^# {{ node_locale }}'
    line: '{{ node_locale }}'

- name: Update default locale 
  template:
    src: locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644

- name: Run dpkg-reconfigure
  command: dpkg-reconfigure -f noninteractive locales

