---
# Install k3s
# General tasks, for both master and nodes

# Info:
#   https://rancher.com/docs/k3s/latest/en/quick-start/
#   https://github.com/rancher/k3s/blob/master/README.md
#   https://github.com/rancher/k3s/blob/master/contrib/ansible/

# Include variables (needed?)
- include_vars: group_vars/vars.yml

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

# https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster
- name: Flushing iptables
  iptables:
    flush: yes

- name: Set iptables v4
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Set iptables v6
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Add cgroup directives to boot command line config
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '((.)+?)(\scgroup_\w+=\w+)*$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes
  register: boot_cmdline

- name: Rebooting if needed
  reboot:
    reboot_timeout: 3600
  ignore_errors: true
  when: ( boot_cmdline.changed )

- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent
  when: install_k3s
