---
# Install k3s on nodes

# Node has the same install, with the addition of:
# - K3S_URL="https://{{ master_ip }}:6443"
# - K3S_TOKEN="{{ token }}"

- name: Installing k3s
  shell: >
    curl -sfL https://get.k3s.io | 
    K3S_URL="https://{{ master_ip }}:6443" 
    K3S_TOKEN="{{ token }}" sh -
  when: install_k3s

- name: Use docker as container runtime
  template:
    src: k3s-agent.service.j2
    dest: /etc/systemd/system/k3s-agent.service
    owner: root
    group: root
    mode: 0644

- name: Restarting k3s-agent service
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: restarted