---
# Install k3s on master

- name: Installing k3s
  shell:
    curl -sfL https://get.k3s.io | sh -
  when: install_k3s

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Read node-token (from master)
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Delegating node-token to nodes
  set_fact: 
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['nodes'] }}"

- name: Restarting k3s-server service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted