---
- name: Activate I2C in config.txt
  # config file: /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "dtparam=i2c_arm"
    line: "dtparam=i2c_arm=on"
  become: yes
    
- name: Activate I2C in /etc/modules
  lineinfile:
    path: /etc/modules
    line: "i2c-dev"
  become: yes  
    

