---

# Install docker
# https://docs.docker.com/install/linux/docker-ce/debian/


# First, disable swap
- name: Disabling swap
  shell: >
      dphys-swapfile swapoff &&
      dphys-swapfile uninstall &&
      update-rc.d -f dphys-swapfile remove
  when:
    - ansible_swaptotal_mb > 0


- name: Removing dphys-swapfile
  apt:
    pkg: dphys-swapfile
    state: absent


# Remove legacy versions of docker
- name: Removing legacy versions of docker (if any)
  apt:
    name:
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
    state: absent


# Install dependencies
- name: Installing dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: present


# Set apt for docker
- name: Adding docker apt key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
  register: add_repository_key
  #ignore_errors: true


- name: Adding docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian/ buster stable
    state: present
    update_cache: true


# Check if docker is installed
- name: Checking for docker
  stat:
    path: /usr/bin/docker
  register: docker_installed


# Install docker if not yet installed
- name: Installling docker
  shell: curl -sSL https://get.docker.com | sudo bash
  args:
    warn: false
  when: docker_installed.stat.exists == false
    

- name: Setting docker to start at boot
  service:
    name: docker
    state: started
    enabled: yes


- name: Adding user pi to the docker group
  user:
    name: pi
    groups: docker
    append: true
